### ISSUE TITLE
ef core 6 (split queries) for included collection navigation get an error

### ISSUE THREAD

**Issue by kliukvinda** [PawelGerr/Thinktecture.EntityFrameworkCore#14]
Thinktecture.EntityFrameworkCore 4.0.0-beta01

dbContext configuration:
![image](https://user-images.githubusercontent.com/94465946/142015948-cd9019b9-a503-4d96-a2e4-447cc97a1284.png)

![image](https://user-images.githubusercontent.com/94465946/142020322-13db97f7-364a-458a-9451-fef9bb841a77.png)

_context.BulkInsertIntoTempTableAsync:
![image](https://user-images.githubusercontent.com/94465946/142019301-a0910e81-1219-423f-b5b4-d25ee89057e4.png)

call example:
![image](https://user-images.githubusercontent.com/94465946/142023217-b3286800-a7a5-4ee3-8534-7938ea1816ce.png)

in the first query the correct table name:
![image](https://user-images.githubusercontent.com/94465946/142018438-efaec8a2-d8ba-4608-aab9-b0635b0adfcb.png)

in the second query, the table name is incorrect and we get an error:
![image](https://user-images.githubusercontent.com/94465946/142018516-e625247a-f7f7-496f-97c6-e980cabb4b43.png)

Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid object name '#TempTable< int >'

Please see what the problem might be?
Thanks.

**Comment by PawelGerr** [comment]
The query splitting behavior "SplitQueries" in projection (i.e. in `Select`) is a new EF Core 6 feature.
EF creates the second query by cloning the query - and that's a problem. I'm loosing important information when the expressions are cloned.

On first glance, it doesn't look like I can fix it (easily) because there are no extensibility points when expressions are being cloned. At the moment I see no other way as disallowing of temp tables in queries with query splitting behavior "SplitQueries" to prevent invalid SQL statements.
